### ISSUE TITLE
Integration with cookie-cutter?

### ISSUE THREAD

**Issue by HemuManju** [hobogalaxy/lightning-hydra-template#75]

**Comment by hobogalaxy** [comment]
Hey @HemuManju,
Thanks for the suggestion!
Could you explain what are the benefits from using cookie-cutter for this particular template, instead of simply using "use this template" button? I feel like apart from automatically setting setup.py parameters and project folder name, there's not much to gain. Not sure if I want to base this repo around it since not everyone knows it.

I might transform it into cookie-cutter version if I change my mind in the future

**Comment by HemuManju** [comment]
Hey @hobogalaxy, 

I agree, there is no much gain by integration. I will be happy to contribute in the future if you decide to add cookie-cutter support.
